env:
 - GHCVER=7.6.3   CABALVER=1.18   CABAL_FLAGS=
 - GHCVER=7.8.4   CABALVER=1.18   CABAL_FLAGS=
 - GHCVER=7.10.2  CABALVER=1.22   CABAL_FLAGS=
 - GHCVER=head    CABALVER=head   CABAL_FLAGS=
 - GHCVER=7.6.3   CABALVER=1.18   CABAL_FLAGS=use-text-show
 - GHCVER=7.8.4   CABALVER=1.18   CABAL_FLAGS=use-text-show
 - GHCVER=7.10.2  CABALVER=1.22   CABAL_FLAGS=use-text-show
 - GHCVER=head    CABALVER=head   CABAL_FLAGS=use-text-show

matrix:
  allow_failures:
   - env: GHCVER=7.6.3   CABALVER=1.18   CABAL_FLAGS=
   - env: GHCVER=head    CABALVER=head   CABAL_FLAGS=
   - env: GHCVER=7.6.3   CABALVER=1.18   CABAL_FLAGS=use-text-show
   - env: GHCVER=head    CABALVER=head   CABAL_FLAGS=use-text-show

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 - cabal --version

install:
 - cabal update
 - cabal install --only-dependencies --enable-tests --flags=$CABAL_FLAGS

script:
 - cabal configure --enable-tests -v2 --flags=$CABAL_FLAGS
 - cabal build 
 - cabal test
 - cabal check
 - cabal sdist 
 - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
