sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - happy-1.19.5
      - libgmp-dev

env:
  - STACK_YAML=stack.yaml           FLAGS="--flag http-api-data:use-text-show"
  - STACK_YAML=stack-ghc-7.8.yaml   FLAGS="--flag http-api-data:use-text-show"
  - STACK_YAML=stack-ghc-7.10.yaml  FLAGS="--flag http-api-data:use-text-show"
  - STACK_YAML=stack.yaml           FLAGS=
  - STACK_YAML=stack-ghc-7.8.yaml   FLAGS=
  - STACK_YAML=stack-ghc-7.10.yaml  FLAGS=

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:/opt/happy/1.19.5/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --version

install:
  - stack setup

script:
  - stack --no-terminal build --test $FLAGS

cache:
  directories:
    - $HOME/.stack
